<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenNetty\OpenNetty.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="OpenNetty" />
    <Using Include="OpenNetty.Mqtt" />
    <Using Include="OpenNetty.OpenNettyResources" Alias="SR" />
  </ItemGroup>

</Project>
